Fix errors linked to psa-crypto-conversions feature
parallaxsecond/rust-cryptoki pull request #202
Opened 2024-03-07 16:51 UTC by gowthamsk-arm

The CI script so far was not testing the psa-crypto-conversions feature and the code bounded by this feature was not updated with changes to the structures in the crate resulting in errors. This patch fixes these errors.

Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

2024-03-07 17:12 UTC, tgonzalezorlandoarm requested changes
small change

2024-03-07 17:12 UTC, tgonzalezorlandoarm commented on ci.sh
> +RUST_BACKTRACE=1 cargo build --all-features
Should we put it higher up with the rest of the build tests?

2024-03-07 18:27 UTC, wiktor-k approved these changes
LGTM 👍 Thanks!

2024-03-08 09:30 UTC, tgonzalezorlandoarm approved these changes

2024-03-08 10:30 UTC, merged