Module tree hygiene
parallaxsecond/rust-cryptoki pull request #56
Opened 2021-10-31 04:26 UTC by vkkoskie

This PR introduces breaking changes. It attempts to resolve Issue #55, which has a more complete description of its rationale.

The changes are almost entirely structural. No function bodies or prototypes have changed, and the overall API is identical. The break comes only in the paths through which external users of the crate access its items. (e.g., `use cryptoki::types::session::Session` is now `use cryptoki::session::Session` but the Session struct is unchanged). The overall effect is a wider, shallower tree, where each module contains conceptually linked types. This produces a much more intuitive "front door" for documentation.

Because file move diffs are often difficult to read, the PR is broken up into a series of commits each with its own detailed commit message to make review easier.

As I was making these changes, I also noticed a general misuse of visibility markers, and I suspect that more of the crate is exposed as pub than is ideal. While I did make several necessary changes from private to pub(crate) in order for moved items to be usable with the new structure, I only made one visibility change unrelated to this PR's primary goal. This is the final commit to the branch and removes the macro_export directive to take the get_pcks11 macro out of the public API (where it wouldn't have compiled anyway).

2021-11-02 00:56 UTC, mjb3279 commented
Any reason not to just delete the `objects` module all together as it's empty and I, at the moment, cannot think of a good reason to keep it?

2021-11-03 15:32 UTC, ionut-arm approved these changes
The changes look sensible to me! Also, I'm happy with the `objects` module being removed.

The imports for that failing doctest should also be fixed, though

2021-11-04 01:45 UTC, vkkoskie commented
New commits. More file moves, which make diffs look much more drastic than they really are. Here's the summary:

To try and respect the prior organization as much as possible, the methods previously located in the `functions` module all still occupy a file of the same name, indicating which section of the specification they belong to. However, all have been changed from methods to private functions in a submodule of the struct they belong to. The struct definition itself exposes these functions through method stubs, which are now also the collection point for method documentation.

This provides what I think is a nice balance between the needs of developers and users of the crate. Users see a uniform struct uncluttered by impl annotations. This makes the struct itself monolithic which would be cumbersome to developers, but instead they get to work in the broken out files nearby.

I wasn't sure if performance was of any concern, but I went ahead and removed the layer of indirection introduced by stubbing by forcing explicit inlining. Even if performance isn't a big concern, it does no harm.

I also found what I *think* is a bug in `Session::close()`, which I believe was intended to take ownership of `self` to trigger a call to `drop()` the same way the library context does. It probably should have been its own Issue/PR, but I didn't think it would be a big deal to include it.

2021-11-04 02:15 UTC, mjb3279 commented on cryptoki/src/session/mod.rs
> +    pub fn close(self) {}
That's a good catch, otherwise `close()` really didn't do anything.

2021-11-04 02:28 UTC, mjb3279 commented
I think I buy why you made those changes in `b711d0c`.  It's definitely drastic but the docs that are generated are significantly improved.

2021-11-04 02:29 UTC, mjb3279 requested changes

2021-11-04 02:29 UTC, mjb3279 commented on cryptoki/src/session/mod.rs
> +    /// ```rust
Let's replace this `rust` with `no_run`

2021-11-04 02:30 UTC, mjb3279 commented on cryptoki/src/session/mod.rs
> +    /// ```rust
```suggestion
    /// ```no_run
```

2021-11-04 02:31 UTC, vkkoskie commented
Hmm. Github CI is unhappy with a part of the code I didn't touch. Maybe the rust image updated to a new version? Just a guess.

2021-11-04 03:04 UTC, mjb3279 commented on cryptoki/src/session/mod.rs
> +    /// use std::env;
I think because of your changes to the layout of the crate, these `use` statements are failing

2021-11-04 03:14 UTC, mjb3279 commented on cryptoki/src/session/mod.rs
> +    /// use std::env;
```suggestion
    /// use cryptoki::context::Pkcs11;
    /// use cryptoki::context::CInitializeArgs;
    /// use cryptoki::object::AttributeType;
    /// use cryptoki::session::UserType;
    /// use cryptoki::session::SessionFlags;
    /// use std::collections::HashMap;
    /// use std::env;
```

2021-11-04 03:28 UTC, mjb3279 commented
Went ahead and made the changes and force pushed an updated commit to contain the 'magic' 'Signed-off-by' line.

2021-11-04 03:29 UTC, mjb3279 approved these changes

2021-11-04 03:31 UTC, merged